#!/bin/sh
set -ev
cd $(dirname $0)

../deploy_qt \
    --headless \
    --installer http://download.qt.io/official_releases/qt/5.12/5.12.2/qt-opensource-linux-x64-5.12.2.run \
    list

../deploy_qt \
    --headless \
    --cleanup \
    --installer /root/workspace/test/qt-opensource-linux-x64-5.12.2.run \
    install \
    --destdir /opt/Qt \
    --packages qt.qt5.5122.qtnetworkauth,qt.qt5.5122.qtwebengine,qt.qt5.5122.gcc_64 \
    --clean-destdir
