#!/bin/sh
set -ev
cd $(dirname $0)/..

# Build & Install
python3 setup.py sdist bdist_wheel
pip3 install dist/cuteci-1.1.0-py3-none-any.whl

# Test Qt 5.12.2
cuteci \
    --installer http://download.qt.io/official_releases/qt/5.12/5.12.2/qt-opensource-linux-x64-5.12.2.run \
    list

cuteci \
    --rm \
    --installer /root/workspace/qt-opensource-linux-x64-5.12.2.run \
    install \
    --verbose \
    --destdir /opt/Qt \
    --packages qt.qt5.5122.qtnetworkauth,qt.qt5.5122.gcc_64
ls /opt/Qt/5.12.2/gcc_64/lib/libQt5NetworkAuth.so


# Test Qt 5.11.3
cuteci \
    --installer http://download.qt.io/archive/qt/5.11/5.11.3/qt-opensource-linux-x64-5.11.3.run \
    list

cuteci \
    --rm \
    --installer /root/workspace/qt-opensource-linux-x64-5.11.3.run \
    install \
    --verbose \
    --destdir /opt/Qt \
    --packages qt.qt5.5113.qtnetworkauth,qt.qt5.5113.gcc_64
ls /opt/Qt/5.11.3/gcc_64/lib/libQt5NetworkAuth.so


# Test Qt 5.10.1
cuteci \
    --installer http://download.qt.io/archive/qt/5.10/5.10.1/qt-opensource-linux-x64-5.10.1.run \
    list

cuteci \
    --rm \
    --installer /root/workspace/qt-opensource-linux-x64-5.10.1.run \
    install \
    --verbose \
    --destdir /opt/Qt \
    --packages qt.qt5.5101.qtnetworkauth,qt.qt5.5101.gcc_64
ls /opt/Qt/5.10.1/gcc_64/lib/libQt5NetworkAuth.so


# Test Qt 5.9.7 + Tools
cuteci \
    --installer http://download.qt.io/archive/qt/5.9/5.9.7/qt-opensource-linux-x64-5.9.7.run \
    list

cuteci \
    --rm \
    --installer /root/workspace/qt-opensource-linux-x64-5.9.7.run \
    install \
    --verbose \
    --destdir /opt/Qt \
    --packages qt.qt5.597.qtnetworkauth,qt.qt5.597.gcc_64 \
    --keep-tools
ls /opt/Qt/5.9.7/gcc_64/lib/libQt5NetworkAuth.so
ls /opt/Qt/Tools
